#     .oooooo.   oooo
#    d8P'  `Y8b  `888
#   888           888   .oooo.   ooo. .oo.    .oooo.o
#   888           888  `P  )88b  `888P"Y88b  d88(  "8
#   888           888   .oP"888   888   888  `"Y88b.
#   `88b    ooo   888  d8(  888   888   888  o.  )88b
#    `Y8bood8P'  o888o `Y888""8o o888o o888o 8""888P'
#                      The ultimate clan plugin
#                                               sekc
#  ===================================================

# When the plugin responds in chat, how should the message look?
clan-message-format: "<grey>[</grey><gradient:#bb88d0:#aa88ff><b>clans</b></gradient><grey>]</grey> "

database:
  # The path to the database (leave default if you want SQLite (no setup required) local database,
  # change this if you want to use a different SQL database)
  filepath: "jdbc:sqlite:plugins/clans/database.db"

leveling:
  # How the level is calculated, it is calculated by the formula:
  #   level = (experience/div)^pow
  div: 100 # how much experience required for first level
  pow: 0.7 # lower = difficulty gets harder faster, should not be set higher than 1
  player-xp-mul: 0.7 # Any time you get xp for your clan, this the xp with this multiplier will be added to your player XP

furnace:
  delayTicks: 120 # How many ticks should it take to burn 1 item?

storage-awards:
  # How the level is calculated, it is calculated by the formula:
  #   level = (experience/div)^pow
  div: 10 # how many levels required for first award
  pow: 0.6 # lower = num levels required increases more each time, should not be set higher than 1

warp-awards:
  # How the level is calculated, it is calculated by the formula:
  #   level = (experience/div)^pow
  div: 10 # how many levels required for first award
  pow: 0.6 # lower = num levels required increases more each time, should not be set higher than 1

clans:
  player-limit: 16 # Maximum 16 players in a clan